name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Signed Release APK
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Checkout code
        uses: actions/checkout@v4

      - name: 2️⃣ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 3️⃣ Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: 4️⃣ Fix gradlew line endings and permission
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix
          dos2unix ./gradlew
          chmod +x ./gradlew

      - name: 5️⃣ Decode release.keystore
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
        run: echo "$KEYSTORE_FILE_BASE64" | base64 --decode > ${{ github.workspace }}/release.keystore

      - name: 6️⃣ Build signed release APK
        env:
          KEYSTORE_PATH:      ${{ github.workspace }}/release.keystore
          KEYSTORE_PASSWORD:  ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS:          ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD:       ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: 7️⃣ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: 8️⃣ Notify Telegram
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | cut -d '"' -f2)
          VERSION_CODE=$(grep 'versionCode' app/build.gradle.kts | grep -o '[0-9]\+')

          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%s)
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
          TIMESTAMP=$(TZ="Asia/Kolkata" date +"%d %b %Y, %I:%M %p")

          # Escape Markdown V2
          escape_markdown() {
            echo "$1" | sed -e 's/[_*[\]()~`>#+=|{}.!-]/\\&/g'
          }

          ESCAPED_MESSAGE=$(escape_markdown "$COMMIT_MESSAGE")
          ESCAPED_AUTHOR=$(escape_markdown "$COMMIT_AUTHOR")

          CAPTION="*✅ Android Build Completed*\n\n\
          *Version:* *v${VERSION_NAME}* (${VERSION_CODE})\n\
          *Commit:* \`${COMMIT_HASH}\`\n\
          *Message:* \`${ESCAPED_MESSAGE}\`\n\
          *Author:* *${ESCAPED_AUTHOR}*\n\
          *Time:* ${TIMESTAMP} (IST)\n\n\
          📦 *Artifact:* app-release.apk"

          FILE="app/build/outputs/apk/release/app-release.apk"
          if [ -f "$FILE" ]; then
            curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
              -F chat_id="${TELEGRAM_CHAT_ID}" \
              -F parse_mode="Markdown" \
              -F document=@"$FILE" \
              -F caption="$CAPTION"
            echo "✅ APK sent to Telegram"
          else
            echo "❌ APK not found"
          fi
